services:
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - '1550:80'
    depends_on:
      - app
    networks:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: "gunicorn --timeout=30 --workers=2 --bind 0.0.0.0:8000 --preload cipe.wsgi:application"
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
      - ./captura_data.env
      - ./cipe_data.env
    networks:
      - postgres

networks:
  postgres:
    name: captura-community-docker_postgres
    external: true

volumes:
  static_volume: