services:
  app:
    restart: always
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - "8000:8000"
      - "5173:5173"
    env_file:
      - ./.env.dev
    networks:
      - postgres

networks:
  postgres:
    name: captura-community-docker_postgres
    external: true
