openapi: 3.0.3
info:
  title: Rohecha API
  version: 1.0.0
  description: API REST de la aplicación Rohecha para consultar denuncias
paths:
  /api/cities/:
    get:
      operationId: api_cities_retrieve
      description: Representa una ciudad que se asocia a una denuncia por medio de
        su id. Los campos "code" y "color" son utilizados para realizar los gráficos
        en la web.
      summary: Lista las ciudades.
      parameters:
      - in: query
        name: id
        schema:
          type: string
        description: Id de la ciudad.
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
  /api/complaint-types/:
    get:
      operationId: api_complaint_types_retrieve
      description: Representa un tipo de denuncia que se asocia a una denuncia por
        medio de su id. Los campos "code" y "color" son utilizados para realizar los
        gráficos en la web.
      summary: Lista los tipos de denuncia.
      parameters:
      - in: query
        name: id
        schema:
          type: string
        description: Id del tipo de denuncia.
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComplaintType'
          description: ''
  /api/complaint-votes/:
    get:
      operationId: api_complaint_votes_list
      description: Los votos tienen el campo "vote_type" para indicar si las denuncias
        ya fueron resueltas (vote_type="Y") o no (vote_type="N"). Se puede utilizar
        el parámetro "complaint-id" para listar las votaciones sobre una denuncia.
      summary: Lista todos los votos hechos en la aplicación.
      parameters:
      - in: query
        name: complaint-id
        schema:
          type: integer
        description: Id de la denuncia.
      tags:
      - api
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComplaintVote'
          description: ''
    post:
      operationId: api_complaint_votes_create
      description: El voto tiene el campo "vote_type" para indicar si ya se resolvió
        la denuncia (vote_type="Y") o no (vote_type="N").
      summary: Realiza una votación sobre el estado de una denuncia.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplaintVoteRequest'
            examples:
              EjemploDeVotación:
                value:
                  vote_type: Y
                  complaint: 0
                summary: Ejemplo de votación
                description: Crea una votación para indicar que la denuncia con id
                  0 SI se resolvió.
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ComplaintVoteRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ComplaintVoteRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComplaintVote'
          description: ''
  /api/complaints/:
    get:
      operationId: api_complaints_list
      description: Lista todas las denuncias según el rango de fechas dado ("start-date"
        y "end-date"), la ciudad ("city-id") o el tipo de denuncia ("complaint-type-id").
        El campo "photo" de la entidad es el enlace dentro de la página para ver la
        foto de la denuncia y descargarla, sin embargo, tener en cuenta que denuncias
        hechas en 2024 pueden tener enlaces pero no fotos disponibles ya que pudieron
        haber sido borradas. El campo "votes" tiene la cuenta de los votos realizados
        sobre la denuncia para determinar si se resolvió (llave "Y") o no (llave "N").
      summary: Lista todas las denuncias.
      parameters:
      - in: query
        name: city-id
        schema:
          type: integer
        description: Id de la ciudad.
      - in: query
        name: complaint-type-id
        schema:
          type: integer
        description: Id del tipo de denuncia.
      - in: query
        name: end-date
        schema:
          type: string
          format: date
        description: 'Fin de rango de fechas de las denuncias. Debe seguir el formato
          YYYY-mm-dd (Ejemplo: "2024-11-05").'
      - in: query
        name: id
        schema:
          type: integer
        description: Id de la denuncia.
      - in: query
        name: start-date
        schema:
          type: string
          format: date
        description: 'Inicio de rango de fechas de las denuncias. Debe seguir el formato
          YYYY-mm-dd (Ejemplo: "2024-11-05").'
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComplaintSerializerRead'
          description: ''
    post:
      operationId: api_complaints_create
      description: Para crear una denuncia se necesitará la ubicación de esta, para
        esto se puede utilizar alguna aplicación de mapas como Google Maps o OpenStreetMap.
      summary: Crea una denuncia.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplaintSerializerWriteRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComplaintSerializerWrite'
          description: ''
  /api/reports/complaints-per-city/:
    get:
      operationId: api_reports_complaints_per_city_retrieve
      description: El formato del reporte está determinado por el campo "report-format"
        que puede ser "csv" o "json" y acepta los parámetros "start-date" y "end-date"
        para determinar que denuncias utilizar para recopilar los datos.
      summary: Retorna el reporte de la cantidad de denuncias hechas por ciudad.
      parameters:
      - in: query
        name: end-date
        schema:
          type: string
        description: 'Fin de rango de fechas de las denuncias. Debe seguir el formato
          YYYY-mm-dd (Ejemplo: "2024-11-05").'
      - in: query
        name: report-format
        schema:
          type: string
          default: csv
        description: Formato del reporte. Puede ser "csv" o "json".
      - in: query
        name: start-date
        schema:
          type: string
        description: 'Inicio de rango de fechas de las denuncias. Debe seguir el formato
          YYYY-mm-dd (Ejemplo: "2024-11-05").'
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/reports/complaints-per-complaint-type/:
    get:
      operationId: api_reports_complaints_per_complaint_type_retrieve
      description: El formato del reporte está determinado por el campo "report-format"
        que puede ser "csv" o "json" y acepta los parámetros "start-date" y "end-date"
        para determinar que denuncias utilizar para recopilar los datos.
      summary: Retorna el reporte de la cantidad de denuncias hechas por tipo de denuncia.
      parameters:
      - in: query
        name: end-date
        schema:
          type: string
        description: 'Fin de rango de fechas de las denuncias. Debe seguir el formato
          YYYY-mm-dd (Ejemplo: "2024-11-05").'
      - in: query
        name: report-format
        schema:
          type: string
          default: csv
        description: Formato del reporte. Puede ser "csv" o "json".
      - in: query
        name: start-date
        schema:
          type: string
        description: 'Inicio de rango de fechas de las denuncias. Debe seguir el formato
          YYYY-mm-dd (Ejemplo: "2024-11-05").'
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/users/token/:
    post:
      operationId: api_users_token_create
      description: Retorna el token de un usuario.
      summary: Retorna el token de un usuario
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthTokenRequestRequest'
            examples:
              Ejemplo:
                value:
                  username: username
                  password: password
                description: Consigue el token del usuario 'username' con la contraseña
                  'password'.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
components:
  schemas:
    AuthToken:
      type: object
      properties:
        token:
          type: string
          readOnly: true
      required:
      - token
    AuthTokenRequestRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - password
      - username
    City:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
        code:
          type: string
          maxLength: 8
        color:
          type: string
          maxLength: 18
      required:
      - code
      - color
      - id
      - name
    ComplaintSerializerRead:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        complaint_type:
          $ref: '#/components/schemas/ComplaintType'
        description:
          type: string
          nullable: true
        city:
          $ref: '#/components/schemas/City'
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        photo:
          type: string
          format: uri
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        votes:
          type: object
          properties:
            Y:
              type: integer
            N:
              type: integer
          required:
          - N
          - Y
          readOnly: true
      required:
      - city
      - complaint_type
      - created_at
      - id
      - latitude
      - longitude
      - votes
    ComplaintSerializerWrite:
      type: object
      properties:
        complaint_type:
          type: integer
        description:
          type: string
          nullable: true
        city:
          type: integer
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        created_at:
          type: string
          format: date-time
          readOnly: true
        photo_base64:
          type: string
      required:
      - city
      - complaint_type
      - created_at
      - latitude
      - longitude
    ComplaintSerializerWriteRequest:
      type: object
      properties:
        complaint_type:
          type: integer
        description:
          type: string
          nullable: true
        city:
          type: integer
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        photo_base64:
          type: string
      required:
      - city
      - complaint_type
      - latitude
      - longitude
    ComplaintType:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
        code:
          type: string
          maxLength: 8
        color:
          type: string
          maxLength: 18
      required:
      - code
      - color
      - id
      - name
    ComplaintVote:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        vote_type:
          $ref: '#/components/schemas/VoteTypeEnum'
        complaint_id:
          type: integer
          readOnly: true
      required:
      - complaint_id
      - id
      - vote_type
    ComplaintVoteRequest:
      type: object
      properties:
        vote_type:
          $ref: '#/components/schemas/VoteTypeEnum'
      required:
      - vote_type
    VoteTypeEnum:
      enum:
      - Y
      - N
      type: string
      description: |-
        * `Y` - Yes
        * `N` - No
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
servers:
- url: https://097l4f27wj.execute-api.us-east-1.amazonaws.com/
  description: API Serverless
- url: /
  description: Servidor local
