# Generated by Django 4.2.16 on 2025-04-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_complaint_captura_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default='TEST', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='color',
            field=models.CharField(default='#ffffff', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainttype',
            name='color',
            field=models.CharField(default='#ffffff', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintvote',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.complaint'),
        ),
    ]
