name: Redeploy Amazon EC2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - develop
jobs:
  Redeploy-Amazon-EC2:
    name: Redeploy Amazon EC2
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST} '
            cd ~/PFC/cipe-captura &&
            git pull
            sudo docker compose up --build -d
          '
